# Generated by Django 3.0.2 on 2020-01-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('bio', models.TextField(max_length=350)),
                ('daily_growth', models.IntegerField(default=0)),
                ('average_comments_per_post', models.IntegerField(default=0)),
                ('average_likes_per_post', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('last_reported', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='instagramusers.Category')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_to_post', models.URLField(max_length=2000, unique=True)),
                ('added_to_ig', models.DateTimeField()),
                ('last_report', models.DateTimeField(auto_now_add=True)),
                ('current_likes', models.IntegerField(default=0)),
                ('current_comments', models.IntegerField(default=0)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instagramusers.InstagramAccount')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccountReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='instagramusers.InstagramAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='instagramusers.Category')),
            ],
        ),
    ]
